[build]
builder = "nixpacks"
buildCommand = "npm run postinstall"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/fetch-data"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 