[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "NODE_ENV=production npm start"
healthcheckPath = "/api/fetch-data"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 